name: My first workflow
on: [push, workflow_dispatch]
jobs:
  my-first-job:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Print env object
        run: echo "${{toJson(env)}}"
        if: true

      - name: Print github object
        run: echo "${{toJson(github)}}"
        if: false

      - name: Print job object
        run: echo "${{toJson(job)}}"

      - name: Print inputs object
        run: echo "${{toJson(inputs)}}"

      - name: Print needs object
        run: echo "${{toJson(needs)}}"

      - name: Print runner object
        run: echo "${{toJson(runner)}}"

      - name: Print secrets object
        run: echo "${{toJson(secrets)}}"

      - name: Print steps object
        run: echo "${{toJson(steps)}}"

      - name: Print vars object
        run: echo "${{toJson(vars)}}"
