name: My first workflow
on: [push, workflow_dispatch]
env:
  EC2_HOST: 13.203.175.237
  EC2_USER: ubuntu
jobs:
  my-first-job:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Print env object
        run:  echo "${{ !false }}"
        if: true
        
      - name: Print
        run:  echo "${{ 10 <= 7 }}"
        if: true
        
      - name: Print
        run:  echo "${{ 1 }}"
        if: true
        
      - name: Print
        run:  echo "${{ 'hi' }}"
        if: true
        
      - name: Print
        run:  echo "${{ null }}"
        if: true
        
      - name: Print
        run:  echo "${{ 7 > 3 && 2 > 1 }}"
        if: true
        
      - name: Print
        run:  echo "${{  true && false }}"
        if: true
        
      - name: Print
        run:  echo "${{ true || false }}"
        if: true
        
      - name: Print
        run:  echo "${{ ! false  }}"
        if: true
        
      - name: Print
        run:  echo "${{  5 > 3 && 2 > 10  }}"
        if: true
        
      - name: Print
        run:  echo "${{  }}"
        if: true

      - name: Print github object
        run: echo "${{toJson(github)}}"
        if: false

      - name: Print job object
        if: github.ref == 'refs/heads/test'
        run: echo "${{toJson(job)}}"

      - name: Print inputs object
        run: echo "${{toJson(inputs)}}"

      - name: Print needs object
        run: echo "${{toJson(needs)}}"

      - name: Print runner object
        run: echo "${{toJson(runner)}}"

      - name: Print secrets object
        run: echo "${{toJson(secrets)}}"

      - name: Print steps object
        run: echo "${{toJson(steps)}}"

      - name: Print vars object
        run: echo "${{toJson(vars)}}"
